### ISSUE TITLE
Verbosity parameter

### ISSUE THREAD

**Issue by abhinavdhere** [tcxxxx/WSIAnalysis#2]
The patch extraction module prints a lot of information during the process which may not be desirable, depending on how the code is used. Adding a verbose parameter to control the level of output should sort this. I'm working on this and would send a PR.

**Comment by tcxxxx** [comment]
> The patch extraction module prints a lot of information during the process which may not be desirable, depending on how the code is used. Adding a verbose parameter to control the level of output should sort this. I'm working on this and would send a PR.

Excited to see this!!! Let me know if any concerns.
